version: "3.1"
services:
  # ngxt:
  #   image: nginx:latest
  #   container_name: nginxt-server
  #   stdin_open: true
  #   tty: true
  #   restart: always
  #   ports:
  #     - 1610:1610
  #   volumes:
  #     - ./infra/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
  #     - ./infra/config/nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:rw
  #     - ./infra/nginx/logs:/var/log/nginx
  #     - /etc/hosts:/etc/hosts
  #     # - ./infra/config/nginx/cert/nginx-selfsigned.key:/etc/nginx/conf.d/private/nginx-selfsigned.key
  #     # - ./infra/config/nginx/cert/nginx-selfsigned.crt /etc/nginx/conf.d/file_crt/nginx-selfsigned.crt
  #   working_dir: /var/www/web
  #   networks:
  #     - zafsoft

  webt:
    image: webt:1.0
    container_name: webt-server
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 1234:1234
    volumes:
      - ./infra/config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./infra/config/nginx/default-web-local.conf:/etc/nginx/conf.d/default.conf:rw
      - ./infra/nginx/logs:/var/log/nginx
      - /etc/hosts:/etc/hosts
      - ./web:/usr/share/nginx/html/web:rw
    networks:
      - zafsoft

  # apis:
  #   image: app:1.0
  #   container_name: api-server
  #   stdin_open: true
  #   tty: true
  #   restart: always
  #   environment:
  #     TZ: "Asia/Jakarta"
  #   ports:
  #     - 1007:1007
  #   volumes:
  #     - ./infra/config/.env.local:/usr/share/nginx/html/api/.env
  #     - ./infra/config/nginx/default-api-local.conf:/etc/nginx/conf.d/default.conf:rw
  #     - ./infra/nginx/logs:/var/log/nginx:rw
  #     - ./api:/usr/share/nginx/html/api:rw
  #   networks:
  #     - zafsoft

  dbt:
    image: mysql:8.0
    container_name: dbt-server
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=4G --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: t12yH4di
      MYSQL_TCP_PORT: 3329
    ports:
      - 3329:3329
    volumes:
      - ./infra/data:/var/lib/mysql
      - /etc/hosts:/etc/hosts
      - ./infra/config/mysql/my.cnf:/etc/my.cnf:rw
      - ./infra/config/mysql:/etc/mysql/conf.d
    networks:
      - zafsoft

  pmat:
    image: phpmyadmin
    container_name: pma-server
    restart: always
    links:
      - dbt
    ports:
      - 8029:80
    environment:
      PMA_HOST: dbt
      PMA_PORT: 3329
      MYSQL_ROOT_PASSWORD: t12yH4di
      UPLOAD_LIMIT: 4G
    depends_on:
      - dbt
    networks:
      - zafsoft

volumes:
  appssock:
networks:
  zafsoft:
    driver: bridge
